import React from 'react';
import HealButtonLink from '../HealButtonLink/HealButtonLink';
import Image from 'next/image';
import hero from './../../Assets/Images/Hero.webp';
import background from './../../Assets/Images/background.webp';

/** Hero Banner Component for Homepage */
const Hero: React.FC = () => {
  return (
    <div data-testid="hero" className="hero">
      <div
        className="bg-cover bg-center bg-heal-background"
        style={{ backgroundImage: `url(${background.src})` }}
      >
        <div className="container mx-auto px-6">
          <div className="lg:flex justify-between">
            <div className="text-white py-44 max-w-xl ">
              <h1
                data-testid="hero-title"
                className="text-4xl font-bold leading-[36px]"
              >
                The HEAL Data Platform
              </h1>
              <p
                data-testid="hero-description"
                className="my-5 mr-8 text-2xl font-normal leading-[36px]"
              >
                is a single web interface which allows visitors to discover,
                access, and analyze data generated by HEAL Studies.
              </p>
              <HealButtonLink href={'/portal'} label={'Search for HEAL Data'} />
            </div>
            <div className="hidden lg:block lg:w-1/2">
              <Image
                data-testid="hero-image"
                src={hero.src}
                width={hero.width}
                height={hero.height}
                alt=""
                className="w-full h-full object-cover"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;
