name: CI
on: push
jobs:
  interaction-and-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24.18.1
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Storybook tests
        run: npm run storybook:test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 24.18.1
      - name: Get Version
        run: npm -v
      - name: Install modules

        run: npm ci
      - name: Run ESLint
        run: npm run lint
